name: Build and test

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Prepare
        run: |
          npm install
          npm run build -- --prod --base-href="/madhamanchiharsha.github.io/"
          cd ./dist
          npm link
          cd ./../..
          pwd
          ls
          npm install -g @angular/cli
          pwd
          ls -la
          cd madhamanchiharsha.github.io
          # ng build --base-href="https://madhamanchiharsha.github.io/madhamanchiharsha.github.io/"
          npm link angular-cli-ghpages
          ng add angular-cli-ghpages

      - name: Deploy
        env:
          publish-branch: gh-pages
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          pwd
          ls
          ng deploy --repo=https://github.com/madhamanchiharsha/madhamanchiharsha.github.io.git --name="madhamanchiharsha" --email="harshavardhanm70@gmail.com" 